name: marlin
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab
  - matplotlib
  - nodejs
  - numpy
  - pandas
  - pip
  - seaborn
  - h5py
  - pymmcore=10.1
  - pyserial
  - pytables
  